version: '3.9'

services:
  auth_db:
    image: postgres
    environment:
    - POSTGRES_USER=${DB_AUTH_USER}
    - POSTGRES_PASSWORD=${DB_AUTH_PASSWORD}
    - POSTGRES_DB=${DB_AUTH_DB}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_AUTH_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_AUTH_USER -d $DB_AUTH_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  auth_service:
    build:
        context: .
        dockerfile: AuthMicroservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=${DB_AUTH_HOST};Port=5432;Database=${DB_AUTH_DB};Username=${DB_AUTH_USER};Password=${DB_AUTH_PASSWORD}
      - AUTH_OPTIONS=Secret=${JWT_SECRET};Issuer=${AUTH_ISSUER};Audience=${AUTH_AUDIENCE}
      - GRPC_ADDRESS=${PROFILE_SERVICE_URL}
    ports:
      - "${AUTH_SERVICE_OPEN_PORT}:8080"
    depends_on:
      auth_db:
        condition: service_healthy
      
volumes:
  auth_db_data: